version: '3'

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    command: npm run dev
