version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    command: bash -c 'sleep 3 && npm test'
    volumes:
      - ./app/.env.example:/app/.env
      - ./.env.example:/.env
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - ".env.example"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME} 
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
