services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile.production
    env_file:
      - ./app/.env.example
    image: koshkarik/devops-for-programmers-project-lvl1:latest
    command: npm test
    volumes:
      - ./app/.env.example:/app/.env
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
