services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile.production
    image: koshkarik/devops-for-programmers-project-lvl1:latest
    volumes:
      - ./app/.env:/app/.env
    command: npm test
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
