name: "build"
on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: copy env
        run: make cp-env
      
      - name: tests
        run: make ci 

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: koshkarik/devops-for-programmers-project-lvl1:latest
