name: "build"
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: tests
        run: docker-compose -f docker-compose.yml up --abort-on-container-exit

      - name: build
        run: docker-compose -f docker-compose.yml build app 

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}

      - name: push
        run: docker-compose -f docker-compose.yml push app 
