name: "build"
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: tests
        run: docker-compose -f docker-compose.yml up --abort-on-container-exit

      - name: build
        run: docker-compose -f docker-compose.yml build app 

      - name: push
        run: docker-compose -f docker-compose.yml push app 
