name: "build"
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: copy env
        run: make cp-env
      
      - name: tests
        run: make ci 

      - name: build
        run: make build 

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: push
        run: make push 
